version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
        - 3306:3306
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d

 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
   
    ports:
        - 30002:80
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql
    
    
    restart: always
  # server:
  #   build: ./server
  #   container_name: node_server_container
  #   depends_on:
  #     - mysql-db
  #   environment:
  #     <<: *common-variables
  #     MYSQL_HOST_IP: mysql
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./server:/app
  #   links:
  #     - mysql-db
  #   command: npm start

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080